---
sidebar: sidebar 
permalink: concept_working_with_inventory_file.html 
keywords: inventory file, file format 
summary: 'Fornisce informazioni sull"utilizzo del file di inventario.' 
---
= Lavorare con il file di inventario
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Il file di inventario è costituito dalle LIF di gestione del cluster dei sistemi idonei per gli aggiornamenti del firmware. Contiene l'elenco dei cluster con informazioni sul nome del file del firmware del disco e dello shelf, laddove applicabile.

Per l'aggiornamento del firmware del Service Processor, i nomi host dei nodi e l'IP SP/BMC sono inclusi nel file di inventario.



== Formato del file di inventario

Di seguito viene riportato un esempio di formato di file di inventario con aggiornamenti del firmware di dischi e shelf:

[listing]
----
clusters:
  - clustername: <cluster management LIF-1>
    disk_fw_file: all.zip
    shelf_fw_file: all_shelf_fw.zip

  - clustername: <cluster management LIF-2>
    disk_fw_file: all.zip
    sp_nodes:
    - hostname: <node hostname 1>
      sp_fw_file: SP_FW_308-03990_11.5.zip
      sp_fw_type: bmc
      sp_fw_ver: '11.5'
      sp_ip: <BMC IP>
    - hostname: <node hostname 2>
      sp_fw_file: SP_FW_308-03991_5.8.zip
      sp_fw_type: sp
      sp_fw_ver: '5.8'
      sp_ip: <SP IP>
----
Nell'esempio, gli aggiornamenti del firmware per shelf e disco sono applicabili al cluster-1 e gli aggiornamenti del firmware per disco e SP/BMC sono applicabili al cluster-2.



== Eliminare un cluster dal file di inventario

Se non si desidera applicare gli aggiornamenti del firmware su un cluster specifico, è possibile rimuovere il cluster dal file di inventario.

Ad esempio, se non si desidera applicare gli aggiornamenti del firmware del disco sul cluster-2, è possibile rimuoverlo dal file di inventario utilizzando il seguente comando:

[listing]
----
clusters:
  - clustername: <cluster management LIF-1>
    disk_fw_file: all.zip
    shelf_fw_file: all_shelf_fw.zip
----
È possibile osservare che tutti i dati del cluster 2 sono stati cancellati.

Se si desidera applicare solo gli aggiornamenti del firmware del disco sul cluster-1 e non gli aggiornamenti del firmware dello shelf, utilizzare il seguente comando:

[listing]
----
clusters:
  - clustername: <cluster management LIF-1>
    disk_fw_file: all.zip
----
È possibile notare che la chiave e il valore di _shelf_fw_file_ sono stati rimossi dal cluster-1.


NOTE: L'aggiunta manuale di cluster o controller non è supportata.
