---
sidebar: sidebar 
permalink: concept_overview_dashboard.html 
keywords: overview, provision, dashboard, widget, watchlist 
summary: Fornisce informazioni su dashboard, elenchi di controllo e widget. 
---
= Comprendere la lista di controllo
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Le liste di controllo consentono di accedere ai sistemi preselezionati all'interno di Digital Advisor in modo rapido e semplice. Se si visualizzano spesso un determinato cliente o un set di sistemi, si consiglia di creare elenchi di controllo. È possibile creare fino a 50 liste di controllo e ciascuna lista di controllo può contenere fino a 15,000 sistemi per categoria o 500 sistemi per numero di serie.

Quando si accede a Digital Advisor per la prima volta, è possibile creare una lista di controllo o cercare un nome cliente, un nome di sito, un nome di gruppo, un StorageGRID, un nome host, Cluster, numero di serie o ID di sistema.

È inoltre necessario conoscere i colori applicati alle schede, che indicano la gravità e il tipo di rischi.
