---
sidebar: sidebar 
permalink: concept_understand_health_check_dashboard.html 
keywords: activeiq, health check, health, HCA, health check dashboard, health check score 
summary: Fornisce informazioni per acquisire dimestichezza con la dashboard di controllo dello stato di salute. 
---
= Scopri di più sulla dashboard Health Check in Digital Advisor
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Il dashboard di controllo dello stato di Digital Advisor fornisce un'analisi puntuale dell'ambiente complessivo.

In base al punteggio del controllo dello stato di salute, è possibile allineare i sistemi storage alle Best practice NetApp consigliate per facilitare la pianificazione a lungo termine. Consente di monitorare tutti i sistemi in esecuzione su software e hardware attraverso un'interfaccia utente centralizzata. I punteggi di Health Check ti consentono di ottenere rapidamente informazioni sui rischi del sistema. I consigli e le Best practice principali consentono di intraprendere azioni per migliorare lo stato di salute della base installata.


NOTE: È possibile accedere al dashboard controllo integrità solo tramite le offerte di servizi NetApp SupportEdge Advisor e SupportEdge Expert.
