---
sidebar: sidebar 
permalink: concept_overview_storage_efficiency.html 
keywords: overview, storage efficiency, deduplication, compression 
summary: 'Fornisce informazioni sul monitoraggio dell"efficienza del sistema storage.' 
---
= Comprendere l'efficienza dello storage
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
La dashboard sull'efficienza dello storage visualizza il rapporto di efficienza dello storage, lo spazio logico utilizzato, lo spazio fisico utilizzato e i dati totali salvati per i sistemi storage che eseguono ONTAP 9.1 e versioni successive. Il rapporto di efficienza e i risparmi sono visibili con e senza copie Snapshot per sistemi AFF, sistemi non AFF o entrambi. È possibile visualizzare le informazioni sull'efficienza dello storage a livello di cluster o di nodo.

I risparmi totali nello storage del cliente possono essere visti per funzionalità di efficienza come deduplica dei volumi, compressione dei volumi, compattazione, volumi FlexClone e copie Snapshot. È inoltre possibile visualizzare i primi 5 sistemi storage con il miglior rapporto di efficienza.

video::8Ge3_0qlyxA[youtube,width=848,height=480]