---
sidebar: sidebar 
permalink: digital-advisor-integration-with-bluexp.html 
keywords: digital advisor, integration, bluexp 
summary: 'Digital Advisor (in precedenza Digital Advisor di Active IQ) è ora completamente integrato con BlueXP. È ora possibile gestire i cluster e accedere a tutte le funzionalità di Digital Advisor dall"interfaccia utente di BlueXP.' 
---
= Integrazione di Digital Advisor con BlueXP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Digital Advisor (in precedenza Digital Advisor di Active IQ) è ora completamente integrato con BlueXP. È ora possibile gestire i cluster e accedere a tutte le funzionalità di Digital Advisor dall'interfaccia utente di BlueXP.

Con BlueXP, gli esperti IT e gli architetti del cloud possono gestire centralmente la propria infrastruttura multi-cloud ibrida. Tutto ciò di cui hai bisogno è un account NetApp Support Site (NSS) per accedere a Digital Advisor in BlueXP.



== Panoramica dell'integrazione

A partire da novembre 2022, gli utenti di Digital Advisor saranno incoraggiati a utilizzare Digital Advisor in BlueXP. Da BlueXP, avrai accesso alla stessa interfaccia di Digital Advisor a cui sei abituato, oltre a molto altro ancora. BlueXP consente di creare e amministrare lo storage cloud (ad esempio, Cloud Volumes ONTAP), utilizzare i servizi dati di NetApp (ad esempio, backup cloud) e controllare molti dispositivi storage on-premise e edge.



== Accedi a Digital Advisor in BlueXP

È possibile accedere a Digital Advisor da BlueXP per gestire il cluster.

.Fasi
. Aprire un browser Web e visitare il sito Web all'indirizzo https://cloudmanager.netapp.com/app-redirect/active-iq["BlueXP"^].
. Selezionare *Accedi con le credenziali del sito di supporto NetApp* e immettere le credenziali.
+
Se in precedenza è stato creato un account di accesso BlueXP utilizzando un'e-mail e una password, è necessario continuare a utilizzare l'opzione di accesso.

. Quando richiesto, accedere con le credenziali del NetApp Support Site.
+
Questo accesso è diverso da quello completato al punto 2. Nella fase 2, hai effettuato l'accesso alla piattaforma BlueXP. Ora stai effettuando l'accesso a Digital Advisor.



*Risultato*

Vengono visualizzate tutte le tue liste di controllo e le configurazioni esistenti e ora puoi utilizzare Digital Advisor come di solito.



== Scopri di più su BlueXP

https://docs.netapp.com/us-en/bluexp-family/index.html["Per ulteriori informazioni, consultare la documentazione di BlueXP"^]
