---
sidebar: sidebar 
permalink: learn_BlueXP_sustainability.html 
keywords: activeiq, sustainability, sustainability score, sustainability dashboard, bluexp, benefits, ONTAP 
summary: Fornisce informazioni sulla sostenibilità che consentono di ridurre il consumo energetico e di raggiungere i propri obiettivi ambientali. 
---
= Scopri la sostenibilità
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
La sostenibilità, come servizio, consente di ridurre il consumo di energia e di lavorare per raggiungere gli obiettivi ambientali. Ciò consente di allineare i sistemi storage con pratiche ecocompatibili e di raggiungere gli obiettivi di sostenibilità.

È possibile utilizzare il dashboard Sustainability per visualizzare il punteggio di sostenibilità e l'utilizzo previsto di potenza, carbonio diretto e calore dal dashboard Sustainability. È possibile regolare la percentuale di riduzione del carbonio per siti specifici. È inoltre possibile visualizzare il punteggio di sostenibilità a livello di cluster. In base al punteggio di sostenibilità, puoi valutare la postura di sostenibilità e implementare le azioni consigliate da NetApp per migliorare il punteggio. Per ulteriori informazioni sul dashboard Sustainability, visitare il sito Web all'indirizzo link:BlueXP_sustainability_dashboard_overview.html["Panoramica della dashboard Sustainability"].


NOTE: La sostenibilità è supportata dai sistemi AFF, sia A-Series che C-Series, dai sistemi FAS e da Cloud Volumes ONTAP.

È possibile visualizzare il seguente video per comprendere il dashboard Sustainability:

video::yNRHeOvbGX8[youtube,width=848,height=480]


== Vantaggi della sostenibilità

La sostenibilità offre i seguenti vantaggi:

* Accelera le performance riducendo il numero di dispositivi storage su cui memorizzare la stessa quantità di dati.
* Ridurre i costi di storage ottimizzando l'utilizzo dei sistemi di storage.
* Riduzione dell'impronta di carbonio utilizzando l'energia rinnovabile nei data center.
* Migliorare l'efficienza energetica attuando politiche efficienti dal punto di vista energetico.

