---
sidebar: sidebar 
permalink: learn-about-sustainability.html 
keywords: activeiq, sustainability, sustainability score, sustainability dashboard, benefits, ontap, netapp console 
summary: Fornisce informazioni sulla sostenibilità che consentono di ridurre il consumo energetico e di raggiungere i propri obiettivi ambientali. 
---
= Scopri la sostenibilità con Digital Advisor
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
La sostenibilità ti consente di ridurre il consumo energetico e di lavorare per raggiungere i tuoi obiettivi ambientali.  Ciò consente di allineare i sistemi di stoccaggio alle pratiche ecocompatibili e di raggiungere gli obiettivi di sostenibilità.

Puoi visualizzare il punteggio di sostenibilità e l'utilizzo previsto di energia, carbonio diretto e calore dalla dashboard di sostenibilità. Puoi regolare la percentuale di mitigazione del carbonio per siti specifici. Puoi anche visualizzare il punteggio di sostenibilità a livello di cluster. In base al punteggio di sostenibilità, puoi valutare la postura di sostenibilità e implementare le azioni raccomandate da NetApp per migliorare il punteggio. Per saperne di più sulla dashboard di sostenibilità, vai su link:sustainability-dashboard-overview.html["Panoramica della dashboard Sustainability"].


NOTE: La sostenibilità è supportata dai sistemi Cloud Volumes ONTAP, AFF (A-Series e C-Series), e-Series, FAS e StorageGRID.

È possibile visualizzare il seguente video per comprendere il dashboard Sustainability:

video::yNRHeOvbGX8[youtube,width=848,height=480]


[[benefits-of-sustainability]]
== Vantaggi della sostenibilità

La sostenibilità offre i seguenti vantaggi:

* Accelera le performance riducendo il numero di dispositivi storage su cui memorizzare la stessa quantità di dati.
* Ridurre i costi di storage ottimizzando l'utilizzo dei sistemi di storage.
* Riduzione dell'impronta di carbonio utilizzando l'energia rinnovabile nei data center.
* Migliorare l'efficienza energetica attuando politiche efficienti dal punto di vista energetico.

