---
settings:
  name: Digital Advisor
  release_notes_autogen:
    release_notes_repo: console-relnotes
  harmony_integration: maestro
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: it-it,us-en,de-de,es-es,fr-fr,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documentazione di Digital Advisor
    url: "/index.html"
  - title: Note di rilascio
    entries:
    - title: Novità
      url: "/reference_new_activeiq.html"
    - title: Limitazioni note
      url: "/reference_limitations_activeiq.html"
  - title: Inizia subito
    entries:
    - title: Guida rapida di Digital Advisor
      url: "/concept_getting_started_2.html"
    - title: Scopri le funzionalità Digital Advisor
      url: "/concept_understand_activeiq_features.html"
    - title: Accedi a Digital Advisor nella console NetApp
      url: "/digital-advisor-integration-with-console.html"
    - title: Scopri di più su Digital Advisor
      url: "/concept_key_terms.html"
    - title: Scopri di più su AutoSupport
      url: "/concept_autosupport.html"
    - title: Accedere a Digital Advisor
      url: "/task_login_activeiq.html"
    - title: Provisioning dell'elenco di controllo
      entries:
      - title: Scopri di più sulle liste di controllo
        url: "/concept_overview_dashboard.html"
      - title: Creare una lista di controllo
        url: "/task_add_watchlist.html"
      - title: Gestire una lista di controllo
        url: "/task_manage_watchlists.html"
    - title: FAQ per il Digital Advisor
      url: reference_aiq_faq.html
  - title: Utilizzare Digital Advisor
    entries:
    - title: Analizzare gli attributi di benessere
      entries:
      - title: Scopri di più sul widget benessere
        url: "/concept_overview_wellness.html"
      - title: Visualizzare i rischi del sistema di archiviazione e adottare misure
          correttive
        url: "/task_view_risk_and_take_action.html"
      - title: Rilevare i rischi per la sicurezza e adottare misure correttive
        url: "/task_increase_protection_against_hackers_and_Ransomware_attacks.html"
      - title: Proteggere i sistemi di archiviazione dai rischi ransomware
        url: "/task_protect_systems_against_ransomware_risks.html"
      - title: Analizzare gli attributi del benessere e riconoscere i rischi
        url: "/task_view_and_acknowledge_risks.html"
      - title: Visualizza la cronologia dei rischi del sistema di archiviazione
        url: "/task_view_wellness_history.html"
      - title: Visualizza i rischi e mitiga i rischi utilizzando Unified Manager o
          Ansible Playbook
        url: "/task_view_risks_remediated_unified_manager.html"
      - title: Utilizzare Digital Advisor per risolvere i rischi critici identificati
        url: "/task_avoid_the_downtime_and_possible_data_loss.html"
      - title: Iscriviti alle notifiche sullo stato del sistema di archiviazione
        url: "/task_subscribe_to_wellness_review_email.html"
      - title: Identificare i rinnovi software e hardware per il sistema di archiviazione
        url: "/task_renew_software_and_hardware.html"
      - title: Visualizza lo stato di salute dei cluster e dei nodi utilizzando il
          widget ClusterViewer
        url: "/task_analyze_wellness_clusters_and_nodes.html"
    - title: Analizzare la sostenibilità del sistema di stoccaggio
      entries:
      - title: Scopri la sostenibilità
        url: "/learn-about-sustainability.html"
      - title: Accedi alla dashboard sulla sostenibilità
        url: "/get_started_sustainability_dashboard.html"
      - title: Scopri le funzionalità della dashboard sulla sostenibilità
        url: "/sustainability-dashboard-overview.html"
      - title: Migliorare il punteggio di sostenibilità del sistema di stoccaggio
        url: "/improve_sustainability_score.html"
    - title: Creazione di un piano di aggiornamento
      entries:
      - title: Scopri come generare un piano di aggiornamento ONTAP
        url: "/upgrade_advisor_overview.html"
      - title: Generare un piano di aggiornamento ONTAP per cluster singoli e multipli
        url: "/generate_upgrade_plan_single_multiple_clusters.html"
      - title: Visualizzare le raccomandazioni per l'aggiornamento del firmware
        url: "/view-firmware-update-recommendations.html"
    - title: Visualizza i dettagli del sistema
      entries:
      - title: Visualizza i dettagli dell'inventario del sistema di archiviazione
        url: "/task_view_inventory_details.html"
      - title: Visualizza i dati delle macchine virtuali disponibili in Data Infrastructure
          Insights
        url: "/task-integrating-with-cloud-insights-to-view-vm-details.html"
      - title: Visualizza i casi di supporto e i dettagli del sistema di archiviazione
          con il widget Valuable Insights
        url: "/task_view_valuable_insight_widget.html"
      - title: Visualizza l'utilizzo della capacità con l'abbonamento NetApp Keystone
        url: "/view_keystone_capacity_utilization.html"
    - title: Identificazione proattiva dei requisiti di sistema
      entries:
      - title: Gestisci i requisiti di capacità del sistema di archiviazione con il
          widget Pianificazione
        url: "/concept_overview_planning.html"
      - title: Identificare i sistemi di stoccaggio che si avvicinano ai limiti di
          capacità
        url: "/task_identify_capacity_system.html"
      - title: Gestisci le soglie di capacità di archiviazione del volume
        url: "/task_avoid_a_volume_filling_up_to_prevent_an_outage.html"
      - title: Determinare se è consigliato un aggiornamento tecnologico per il sistema
          di archiviazione
        url: "/evaluate-tech-refresh.html"
      - title: Rinnovare il software e l'hardware del sistema di archiviazione
        url: "/task_renew_software_and_hardware.html"
    - title: Analizza lo stato del sistema di archiviazione con i consigli del cloud
      url: "/task-informed-decisions-based-on-cloud-recommendations.html"
    - title: Identificare la deviazione della configurazione
      entries:
      - title: Rilevare deviazioni di configurazione per il sistema di archiviazione
        url: "/concept_overview_config_drift.html"
      - title: Aggiungi un modello di configurazione per il sistema di archiviazione
        url: "/task_add_config_drift_template.html"
      - title: Confronta i modelli di deriva della configurazione
        url: "/task_compare_config_drift_template.html"
      - title: Genera un report sulla cronologia delle deviazioni di configurazione
        url: "/task_generate_drift_timeline_report.html"
      - title: Gestisci i modelli di deriva della configurazione
        url: "/task_manage_template.html"
    - title: Migliorare l'efficienza e le prestazioni del sistema di archiviazione
      entries:
      - title: Visualizza i risparmi in termini di capacità ed efficienza di archiviazione
        url: "/task_analyze_storage_efficiency.html"
      - title: Visualizza i grafici delle prestazioni del sistema di archiviazione
        url: "/task_view_performance_graphs.html"
    - title: Analizza lo stato di salute del sistema di archiviazione
      entries:
      - title: Scopri di più sulla dashboard di Health Check
        url: "/concept_understand_health_check_dashboard.html"
      - title: Iniziare con il dashboard Health Check
        url: "/concept_get_started_with_health_check_dashboard.html"
      - title: Rinnovare i contratti di supporto
        url: "/task_renew_support_contracts_for_your_systems.html"
    - title: Effettua l'aggiornamento per ottimizzare la base di installazione
      entries:
      - title: Offerta di supporto per l'aggiornamento
        url: "/task_upgrade_support_offering.html"
      - title: Aggiornare il firmware AFF e FAS utilizzando Ansible Playbook
        entries:
        - title: Scarica il pacchetto Ansible del firmware AFF e FAS
          url: "/task_update_AFF_FAS_firmware.html"
        - title: Aggiornare il firmware AFF e FAS utilizzando un pacchetto Ansible
            (utenti esperti)
          url: "/task_install_execute_firmware_update_exp_user.html"
        - title: Installare ed eseguire il pacchetto di automazione Ansible del firmware
            AFF e FAS (principianti)
          entries:
          - title: Ospitare i file del firmware AFF e FAS su un server web
            url: "/task_hosting_firmware_files_using_web_server.html"
          - title: Aggiorna il file di inventario per l'aggiornamento del firmware
              AFF e FAS
            url: "/concept_working_with_inventory_file.html"
          - title: Eseguire il playbook Ansible utilizzando l'immagine Docker NetApp
            url: "/task_execute_ansible_playbook_using_docker.html"
          - title: Eseguire il playbook Ansible senza l'immagine NetApp Docker
            url: "/task_execute_ansible_playbook_without_docker.html"
          - title: Convalida l'installazione del firmware AFF e FAS sul sistema di
              archiviazione
            url: "/task_validate_firmware_installation.html"
    - title: Integrare i dati utilizzando le API
      entries:
      - title: Scopri di più sui servizi API Digital Advisor
        url: "/concept_overview_API_service.html"
      - title: Genera token per utilizzare i servizi API Digital Advisor
        url: "/task_generate_tokens_API_services.html"
      - title: Utilizzare il catalogo API Digital Advisor per eseguire le API
        url: "/task_view_API_catalog.html"
    - title: Generare report personalizzati
      entries:
      - title: Scopri di più sui report Digital Advisor
        url: "/concept_report_types.html"
      - title: Genera o pianifica un report
        url: "/task_generate_reports.html"
  - title: Conoscenza e supporto
    entries:
    - title: Registrati per ricevere assistenza
      url: "/reference_ansible_troubleshoot_feedback_support.html"
    - title: Richiedi assistenza
      url: "/concept_get_more_information.html"
  - title: Note legali
    url: "/legal-notices.html"
product-family:
  name: NetApp Console
  repo: console-family
