---
sidebar: sidebar 
permalink: task_view_valuable_insight_widget.html 
keywords: valuable insight, support cases, storage efficiency savings, mitigated risks 
summary: Fornisce informazioni sul prezioso widget Insight. 
---
= Visualizza i casi di supporto e i dettagli del sistema di archiviazione con il widget Valuable Insights in Digital Advisor
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Il widget *preziose informazioni* fornisce informazioni sul numero di casi di supporto, sugli aggiornamenti software in sospeso, sui risparmi in termini di efficienza dello storage, sui rischi mitigati e altro ancora. Inoltre, elenca in modo proattivo le notifiche di rischio dall'attributo *Wellness*.

video::QPJY2TWnRxQ[youtube,width=848,height=480]
.Fasi
. Nel widget *Inventario*, seleziona *Sistemi* per visualizzare le informazioni di sistema di tutte le piattaforme oppure seleziona il tipo di piattaforma e poi seleziona *Sistemi* per visualizzare i sistemi specifici di quella piattaforma.
. Seleziona il nodo o il cluster per visualizzare informazioni dettagliate sul sistema.
+
Il widget *preziose informazioni* è disponibile nella dashboard.

. Esaminare le informazioni nel widget per comprendere il valore tecnico e commerciale ricevuto dal contratto di supporto.

