---
sidebar: sidebar 
permalink: task_subscribe_to_wellness_review_email.html 
keywords: wellness, wellness review subscription, unsubscribe, supportedge expert, supportedge advisor 
summary:  
---
= Iscriviti alle notifiche sullo stato del sistema di archiviazione da Digital Advisor
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Puoi iscriverti all'email di revisione del benessere per ricevere un'email mensile che riassume lo stato di benessere, i sistemi di storage che si avvicinano alla data di rinnovo e i sistemi di storage che richiedono un aggiornamento per i prodotti NetApp nella tua base installata. Riceverai un'e-mail di verifica dello stato di salute, così potrai visualizzare un riepilogo mensile e intervenire sui tuoi sistemi di archiviazione. Hai anche la possibilità di visualizzare, modificare, condividere ed eliminare i tuoi abbonamenti. In qualsiasi momento, se decidi di non ricevere più l'email, puoi annullare l'iscrizione alla ricezione delle email.

Una volta attivato l'abbonamento, selezionare una data di inizio quando si aggiunge un abbonamento. Il riepilogo mensile dell'e-mail fornisce una panoramica delle azioni di verifica dello stato di salute, rinnovo, aggiornamento e verifica dello stato di salute. È possibile confermare l'indirizzo e-mail e l'e-mail viene inviata all'indirizzo e-mail specificato. È inoltre possibile eliminare gli abbonamenti.


NOTE: Questa funzione è disponibile solo attraverso le offerte di servizi NetApp SupportEdge Advisor e SupportEdge Expert.

.Fasi
. Nel riquadro di sinistra, fare clic su *Wellness Review*.
. Fare clic su *Aggiungi abbonamento*.
. Inserire le informazioni richieste nei campi *Nome abbonamento*, *Scegli categoria*, *Ricerca cliente* e *e-mail* della finestra di dialogo *Aggiungi nuovo abbonamento*.
. Fare clic su *Subscribe* (Iscriviti).
+
Una volta completata l'iscrizione, riceverai un messaggio *l'abbonamento è stato aggiunto*.


