---
sidebar: sidebar 
permalink: task_view_wellness_history.html 
keywords: wellness history, risks, wellness, view all actions, risk history 
summary: Fornisce informazioni sui rischi di sistema e su come visualizzare la cronologia delle condizioni di salute. 
---
= Visualizza la cronologia dei rischi del tuo sistema di archiviazione in Digital Advisor
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
È possibile visualizzare i rischi del sistema di archiviazione verificatisi negli ultimi tre mesi, in modo da poter capire come si stanno comportando nel tempo.

Questi rischi sono classificati in quattro tipi di rischi: *Non risolti*, *nuovi*, *risolti* e *riconosciuti*. Sono rappresentati da colori diversi. Il riepilogo di questi rischi è rappresentato da un grafico *Risk History*.

.Fasi
. Nella dashboard, nel riquadro *Wellness*, seleziona *View All Actions*.
. Seleziona *Cronologia benessere*.
. Nel grafico *Cronologia dei rischi*, seleziona la categoria per cui vuoi vedere la cronologia dei rischi.
+
Passando il mouse sopra le barre colorate, vengono visualizzate informazioni sul numero di rischi in ciascuna categoria. Quando selezioni la rispettiva categoria di rischio, le informazioni vengono visualizzate nella tabella *Risk Information*.

+
Puoi anche scaricare il riepilogo dei rischi in un foglio Excel.


