---
sidebar: sidebar 
permalink: task_view_API_catalog.html 
keywords: API Catalog, APIs, integrate data, view catalog 
summary: Fornisce informazioni sulle API disponibili nel catalogo API. 
---
= Utilizzare il catalogo API per eseguire le API
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Il catalogo API consente di sfogliare le categorie e le API disponibili all'interno di ciascuna di queste categorie.

Utilizzando un token di accesso valido e gli input corretti per i campi obbligatori, è possibile effettuare una chiamata di prova per un'API.



== Accedi alle API GraphQL

.Fasi
. Dal menu *Quick Links* (Collegamenti rapidi), fare clic su *API Services* (servizi API).
. Cliclink:https://activeiq.netapp.com/catalog/internal/api-reference/introduction["Sfoglia"] sotto l'icona *Catalogo API*.
+
Viene visualizzato il catalogo API.

. Fare clic su *GraphQL* e consultare la documentazione.
. Prova le API GraphQL utilizzando le query di esempio pronte per l'esecuzione sulink:https://studio.apollographql.com/public/ActiveIQ-Graph-Prd-API/variant/current/explorer?collectionId=251c50ce-797e-4549-bb9c-f6557ef5a176OPERATION_COLLECTIONfocusCollectionId=251c50ce-797e-4549-bb9c-f6557ef5a176["Digital Advisor GraphQL Studio"^] .
. Fornire un token utente selezionando il campo di autorizzazione nell'intestazione della richiesta API
. Fornire le variabili richieste
. Esegui la query e rivedi l'output




== Accedi alle API REST

.Fasi
. Dal menu *Quick Links* (Collegamenti rapidi), fare clic su *API Services* (servizi API).
. Cliclink:https://activeiq.netapp.com/catalog/internal/api-reference/introduction["Sfoglia"] sotto l'icona *Catalogo API*.
+
Viene visualizzato il catalogo API.

. Fare clic su *ActiveIQ-Public* e selezionare un'API qualsiasi
. Nella parte superiore della pagina, spostare il pulsante su "Experiment" (esperimento).
. Dalla barra di navigazione a sinistra, espandere le categorie e selezionare qualsiasi API per visualizzare informazioni dettagliate.
. Espandere l'API.
. Fare clic sul pulsante *Try it out* (prova) a destra.
. Fornire i parametri richiesti e fare clic su *Esegui* per visualizzare i risultati.
+
È inoltre possibile esaminare la sezione *Responses* dell'API per comprendere meglio i dati che verranno restituiti. È possibile fare clic su *valore di esempio* per visualizzare il formato dei dati oppure fare clic su *modello* e fare clic sui cart per espandere le sezioni per visualizzare la definizione di ciascun elemento.



Facendo scorrere il pulsante di selezione sulla vista *Code*, è possibile visualizzare gli esempi di codice in varie lingue.
