---
sidebar: sidebar 
permalink: task_view_risk_and_take_action.html 
keywords: wellness, performance, efficiency, availability, capacity, security vulnerabilities, protection, protect, mitigate, rectify 
summary: Fornisce informazioni per visualizzare e analizzare lo stato di salute del sistema storage e mitigarne i rischi. 
---
= Visualizza i rischi del sistema di archiviazione in Digital Advisor e adotta misure correttive
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
È possibile analizzare gli attributi di benessere del sistema storage visualizzando le azioni e i rischi associati. È necessario visualizzare le azioni correttive associate e mitigare manualmente il rischio.

.Fasi
. Seleziona il widget *Wellness* nella dashboard oppure seleziona *Visualizza tutte le azioni* per visualizzare l'elenco di tutte le azioni e i rischi.
. Visualizzare le voci *azioni* e *rischi* associate all'attributo wellness.
. Seleziona *Azioni* per visualizzare i rischi associati alle azioni, seleziona *Rischi* per visualizzare tutti i rischi oppure seleziona *Sistemi interessati* per visualizzare i sistemi che richiedono attenzione.
. Seleziona il nome del rischio per visualizzare le informazioni sul rischio.
. Seleziona le azioni correttive associate e segui le informazioni per risolvere il rischio.


I passaggi per mitigare i rischi sono gli stessi per tutti gli attributi di benessere. È possibile visualizzare il seguente video per monitorare e risolvere i problemi relativi alla sicurezza:

video::ssXI-FAKMis[youtube,width=848,height=480]