---
sidebar: sidebar 
permalink: task_analyze_storage_efficiency.html 
keywords: renew, hardware, software 
summary: 'Fornisce informazioni per rinnovare il software e l"hardware del sistema storage.' 
---
= Visualizza i risparmi in termini di capacità ed efficienza di archiviazione in Digital Advisor
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
È possibile visualizzare i dettagli della capacità e i risparmi in termini di efficienza dello storage del sistema e intraprendere le azioni appropriate. Le informazioni sulla capacità e sull'efficienza dello storage possono essere visualizzate a livello di cluster o di nodo.


NOTE: Questa funzione non è supportata nei sistemi e-Series.

Il dashboard della capacità visualizza i dettagli della capacità e la previsione della capacità del sistema. La previsione della capacità utilizza le informazioni storiche sulla capacità per identificare l'utilizzo di ciascun sistema. In base ai dati storici (dati di un anno, se disponibili) della capacità utilizzata e allocata, l'algoritmo considera l'utilizzo corrente di ciascun sistema e genera una previsione per l'utilizzo del sistema nei prossimi 1-6 mesi.

La dashboard per l'efficienza dello storage visualizza il rapporto per la riduzione dei dati, lo spazio logico utilizzato, lo spazio fisico utilizzato e i dati totali salvati per i sistemi storage che eseguono ONTAP 9,1 e versioni successive. Il rapporto di riduzione dei dati e i risparmi sono visibili con e senza copie Snapshot per sistemi AFF, non AFF o entrambi. I risparmi complessivi dei dati nello storage dei clienti possono essere rilevati per le funzionalità di efficienza come deduplica dei volumi, compressione dei volumi, compaction, volumi FlexClone e copie Snapshot. Puoi visualizzare i primi 5 sistemi storage con il miglior rapporto di efficienza. Puoi anche vedere l'efficienza di SAN e NAS senza copie Snapshot a livello di nodo per i sistemi ONTAP inclusi AFF A-Series, AFF C190, All SAN Array e FAS500 con ONTAP 9,10 e versioni successive.

video::8Ge3_0qlyxA[youtube,width=848,height=480]
.Fasi
. Nel riquadro di sinistra, fare clic su *capacità ed efficienza*.
+
Per impostazione predefinita, è selezionata la scheda *Capacity*.

. Visualizzare i dettagli della capacità a livello di cluster e nodo.
+
.. Visualizza la previsione della capacità a livello di nodo.
+
Per i sistemi ONTAP, le informazioni sulla capacità RAW sono disponibili in ClusterViewer.

.. Fare clic su *Add Capacity* (Aggiungi capacità) per inviare una notifica a NetApp o al partner per aggiungere capacità.


. Visualizza l'efficienza dello storage e i risparmi sui dati del tuo sistema storage.
+
.. Se il rapporto di efficienza dello storage del tuo sistema è superiore al rapporto di efficienza dello storage medio, fai clic su *Condividi la tua storia di successo* per farci conoscere le Best practice seguite.
.. Se il rapporto di efficienza dello storage del sistema è inferiore al rapporto di efficienza dello storage medio, fare clic su *Contattaci* per conoscere le configurazioni del sistema storage.




Per ulteriori informazioni sulla capacità e sull'efficienza dello storage, vedere link:reference_aiq_faq.html["Domande frequenti su Digital Advisor"].
