---
sidebar: sidebar 
permalink: task_view_inventory_details.html 
keywords: inventory, platforms, systems, clusters, sites 
summary: 'Fornisce informazioni sull"inventario complessivo di proprietà dell"utente.' 
---
= Visualizza i dettagli dell'inventario del tuo sistema di archiviazione in Digital Advisor
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Il widget *Inventario* fornisce un riepilogo di tutti i sistemi e degli switch autorizzati al supporto di cui sei proprietario.  Sono inclusi sia i prodotti abilitati che quelli non abilitati Digital Advisor .

È inoltre possibile generare il report dell'elenco di controllo selezionato e inviarlo via email a un massimo di 5 destinatari.

video::ttbpbT5uTBI[youtube,width=848,height=480]


== Visualizza i dettagli del sistema

.Fasi
. Nel widget *Inventory* (inventario), fare clic su *Systems* (sistemi) per visualizzare le informazioni di sistema di tutte le piattaforme oppure fare clic sul tipo di piattaforma, quindi su *Systems* (sistemi) per visualizzare i sistemi specifici di tale piattaforma.
. Fare clic sul nodo o sul cluster per visualizzare informazioni dettagliate sul sistema.
. Scarica il report *Inventory* per visualizzare i dettagli del sistema in formato .xls.
. Scarica il report *Ansible Inventory* per visualizzare i dettagli del sistema nei formati .yml e .ini a livello di area geografica o sito.
+
I file Ansible Inventory possono essere utilizzati con file Ansible Playbook personalizzati per apportare modifiche alla configurazione dell'infrastruttura.





== Visualizza i dettagli del supporto autorizzato

.Fasi
. Nel widget *Inventario*, fare clic su *Switch autorizzati al supporto* per visualizzare informazioni su tutti gli switch autorizzati al supporto.

