---
sidebar: sidebar 
permalink: task_protect_systems_against_ransomware_risks.html 
keywords: ransomware, risks, ransomware risks 
summary:  
---
= Proteggi i sistemi di archiviazione gestiti da Digital Advisor dai rischi ransomware
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Quando accedi a Digital Advisor, puoi visualizzare le *azioni* evidenziate nel widget *sicurezza e difesa dal ransomware*, che mostra i conteggi dei rischi.

Puoi visualizzare i rischi relativi alla creazione e alla conservazione degli snapshot e i rischi di ONTAP FPolicy, e poi intraprendere azioni per risolverli.

.Fasi
. Accedere a Digital Advisor.
. Fare clic su *azioni* nel widget *sicurezza e difesa dal ransomware*.
. Deselezionare la casella di controllo *vulnerabilità di protezione*.
. Per i rischi visualizzati, controllare il livello di impatto e seguire le azioni consigliate.
. Fare clic sulla scheda rischi univoci e sul collegamento nella colonna *azione correttiva*.
. Fare clic sulla scheda *sistemi interessati* per visualizzare i sistemi con rischi.
. Seguire le azioni correttive consigliate per proteggere i sistemi.

