---
sidebar: sidebar 
permalink: task-integrating-with-cloud-insights-to-view-vm-details.html 
keywords: Cloud Insights, VMs, virtual machines, Data Infrastructure Insights 
summary: Fornisce informazioni sulle macchine virtuali in Data Infrastructure Insights 
---
= Utilizzare Digital Advisor per visualizzare i dati delle macchine virtuali disponibili in Data Infrastructure Insights
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Digital Advisor è ora integrato con la versione Basic Data Infrastructure Insights per fornire ai clienti un inventario completo e controlli di interoperabilità.

I vantaggi di questa integrazione sono:

* Monitoraggio SaaS semplificato di ONTAP
* Visibilità sul monitoraggio full-stack VMware
* Risparmi di produttività per i clienti grazie a controlli automatizzati dell'interoperabilità per agevolare la pianificazione dell'upgrade di ONTAP. Ciò consente aggiornamenti ONTAP più fluidi e riduce i rischi di incompatibilità con gli host.



NOTE: Questa funzione è disponibile solo per i contratti di aggiornamento di SupportEdge Advisor, SupportEdge Expert e Digital Advisor.

.Fasi
. Nel widget *Inventario*, fare clic su *Macchine virtuali* per visualizzare i dati disponibili in Data Infrastructure Insights.
. Fare clic sulla scheda *Panoramica macchina virtuale*.
. Fare clic su *numero di host ESX* per visualizzare le informazioni sull'host.
. Fare clic su *Nome ESX* per accedere a Data Infrastructure Insights e visualizzare ulteriori informazioni.

