---
sidebar: sidebar 
permalink: task_login_activeiq.html 
keywords: login, log in 
summary: 'Fornisce informazioni per l"accesso a Digital Advisor.' 
---
= Accedere a Digital Advisor
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
È possibile accedere a Digital Advisor da una console basata su Web per visualizzare lo stato generale del sistema di storage.

.Prima di iniziare
Per accedere a Digital Advisor, è necessario disporre di una credenziale valida per il sito del supporto NetApp. Se non disponi di un account e stai per iniziare, consulta il seguente articolo della Knowledge base per creare un account:
link:https://kb.netapp.com/Support/General_Support/How_to_register_for_a_NetApp_Support_Site_account_as_a_Customer_or_a_Guest_user["Come registrarsi per l'account del sito di assistenza NetApp come cliente o utente ospite"^].

.Fasi
. Accedere alla link:https://activeiq.netapp.com/?source=onlinedocs["Consulente digitale"^] pagina di accesso.
+
Digital Advisor mostra i sistemi con un contratto di supporto valido. Se i contratti scadono, viene assegnato un periodo di tolleranza di 90 giorni in cui i sistemi continuano a essere visibili. In seguito, i sistemi non possono essere ricercati o visualizzati in Digital Advisor.

. Inserisci il tuo nome utente e la password e fai clic su *Accedi*.

