---
sidebar: sidebar 
permalink: task_analyze_storage_efficiency.html 
keywords: capacity, storage efficiency, data reduction, savings 
summary: Visualizza i dettagli sulla capacità e i risparmi di efficienza dello storage per il tuo sistema storage. 
---
= Visualizza i risparmi in termini di capacità ed efficienza di archiviazione in Digital Advisor
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
È possibile visualizzare i dettagli della capacità e i risparmi in termini di efficienza dello storage del sistema e intraprendere le azioni appropriate. Le informazioni sulla capacità e sull'efficienza dello storage possono essere visualizzate a livello di cluster o di nodo.


NOTE: Questa funzione non è supportata nei sistemi e-Series.

La dashboard della capacità visualizza i dettagli della capacità e la previsione della capacità del tuo sistema. La previsione della capacità utilizza le informazioni storiche sulla capacità per identificare l'utilizzo di ciascun sistema. In base ai dati storici (i dati di un anno, se disponibili) relativi alla capacità utilizzata e allocata, l'algoritmo considera l'utilizzo attuale di ciascun sistema e genera una previsione per l'utilizzo del sistema nei prossimi 1-6 mesi.

Il pannello di controllo dell'efficienza dello storage visualizza il rapporto di riduzione dei dati, lo spazio logico utilizzato, lo spazio fisico utilizzato e il totale dei dati risparmiati. Il rapporto di riduzione dei dati e il risparmio possono essere visualizzati con e senza copie snapshot per sistemi AFF, sistemi non AFF o entrambi. Il totale dei dati risparmiati sull'intero storage dei clienti può essere visualizzato per ciascuna funzionalità di efficienza, come la deduplicazione dei volumi, la compressione dei volumi, la compaction, i volumi FlexClone e le copie snapshot. Puoi visualizzare i 5 sistemi storage con il miglior rapporto di efficienza. Puoi anche visualizzare l'efficienza SAN e NAS senza copie snapshot a livello di nodo per i sistemi ONTAP, inclusi AFF A-Series, AFF C190, All SAN Array e FAS500.

video::8Ge3_0qlyxA[youtube,width=848,height=480]
.Fasi
. Nel riquadro di sinistra, fare clic su *capacità ed efficienza*.
+
Per impostazione predefinita, è selezionata la scheda *Capacity*.

. Visualizzare i dettagli della capacità a livello di cluster e nodo.
+
.. Visualizza la previsione della capacità a livello di nodo.
+
Per i sistemi ONTAP, le informazioni sulla capacità RAW sono disponibili in ClusterViewer.

.. Fare clic su *Add Capacity* (Aggiungi capacità) per inviare una notifica a NetApp o al partner per aggiungere capacità.


. Visualizza l'efficienza dello storage e i risparmi sui dati del tuo sistema storage.
+
.. Se il rapporto di efficienza dello storage del tuo sistema è superiore al rapporto di efficienza dello storage medio, fai clic su *Condividi la tua storia di successo* per farci conoscere le Best practice seguite.
.. Se il rapporto di efficienza dello storage del sistema è inferiore al rapporto di efficienza dello storage medio, fare clic su *Contattaci* per conoscere le configurazioni del sistema storage.




Per ulteriori informazioni sulla capacità e sull'efficienza dello storage, vedere link:reference_aiq_faq.html["Domande frequenti su Digital Advisor"].
