---
sidebar: sidebar 
permalink: task_identify_capacity_system.html 
keywords: capacity, space, increase, 
summary: Fornisce informazioni per aumentare la capacità del sistema. 
---
= Identificare i sistemi che raggiungono i limiti di capacità
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Identificazione proattiva dei sistemi che raggiungono i limiti di capacità e invio di una richiesta tramite chat live per aumentare la capacità del sistema storage.

È possibile visualizzare i sistemi che hanno superato il 90% della capacità o che devono superare il 90% della capacità in 1, 3 e 6 mesi. Chatta con un addetto alle vendite per aumentare facilmente le richieste di aggiunta di capacità e ottenere assistenza in tempo reale.

.Fasi
. Nel widget *Planning* (Pianificazione), fare clic su *Capacity addizioni* per visualizzare i sistemi che hanno superato il 90% della capacità o si stanno avvicinando al 90% della capacità.
+
È possibile visualizzare il numero di sistemi che hanno superato il 90% della capacità o che devono superare il 90% della capacità nei prossimi 1, 3 e 6 mesi.

. Selezionare una scheda per visualizzare i sistemi.
. Selezionare i sistemi per i quali si desidera aumentare la capacità e fare clic su *Contatta il reparto vendite*.
. Verificare i dettagli di contatto.
. Copia e incolla fino a cinque nomi host nella chat per aumentare le richieste di aggiunta di capacità.

