---
sidebar: sidebar 
permalink: task_view_wellness_history.html 
keywords: wellness history, risks, wellness, view all actions, risk history, 
summary: Fornisce informazioni sui rischi di sistema e su come visualizzare la cronologia delle condizioni di salute. 
---
= Visualizza la cronologia dei rischi del tuo sistema di archiviazione in Digital Advisor
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
È possibile visualizzare i rischi del sistema di archiviazione verificatisi negli ultimi tre mesi, in modo da poter capire come si stanno comportando nel tempo.

Questi rischi sono classificati in quattro tipi di rischi: *Non risolti*, *nuovi*, *risolti* e *riconosciuti*. Sono rappresentati da colori diversi. Il riepilogo di questi rischi è rappresentato da un grafico *Risk History*.

.Fasi
. Nella dashboard, nel riquadro *Wellness*, fare clic su *View All Actions* (Visualizza tutte le azioni).
. Fare clic su *Wellness History*.
. Nel grafico *Risk History*, fare clic sulla categoria per la quale si desidera visualizzare la cronologia dei rischi.
+
Quando si passa il mouse sulle barre colorate, vengono visualizzate informazioni sul numero di rischi in ciascuna categoria. Facendo clic sulla rispettiva categoria di rischio, le informazioni vengono visualizzate nella tabella *informazioni sul rischio*.

+
Puoi anche scaricare il riepilogo dei rischi in un foglio Excel.


