---
sidebar: sidebar 
permalink: task_view_and_acknowledge_risks.html 
keywords: wellness, performance, efficiency, availability, capacity, security vulnerabilities, protection, protect, acknowledge, unacknowledge, disregard 
summary: Fornisce informazioni per visualizzare e analizzare lo stato di salute del sistema storage e riconoscere i rischi. 
---
= Analizza gli attributi del benessere in Digital Advisor e riconosci i rischi
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
È possibile analizzare gli attributi di benessere del sistema storage visualizzando le azioni e i rischi associati. È necessario visualizzare le azioni correttive e mitigare manualmente il rischio.

.Fasi
. Seleziona il widget dell'attributo benessere nella dashboard oppure seleziona *Visualizza tutte le azioni* per visualizzare l'elenco di tutte le azioni e i rischi.
. Visualizzare le voci *azioni* e *rischi* associate all'attributo wellness.
. Seleziona *Azioni* per visualizzare i rischi associati alle azioni, seleziona *Rischi* per visualizzare tutti i rischi oppure seleziona *Sistemi interessati* per visualizzare i sistemi che richiedono attenzione.
. Seleziona il rischio per visualizzare il riepilogo del rischio.
. Seleziona *Ack* per accettare il rischio.
+
Le informazioni dettagliate sul riepilogo dei rischi vengono fornite insieme alle azioni correttive che devono essere eseguite manualmente per mitigare il rischio.

. Se non vuoi o non puoi mitigare il rischio in questo momento, inserisci i valori per i campi e seleziona *Confermo*.
+
Il rischio verrà aggiunto ai rischi riconosciuti.




NOTE: Se non vuoi più che un rischio venga riconosciuto, puoi ignorare il rischio selezionando *Annulla conferma* e seguendo gli stessi passaggi.
