---
sidebar: sidebar 
permalink: task_identify_capacity_system.html 
keywords: capacity, space, increase, ontap systems, storagegrid, storage expansion 
summary: Fornisce informazioni per aumentare la capacità del sistema. 
---
= Identificare i sistemi di archiviazione che si avvicinano ai limiti di capacità in Digital Advisor
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Identifica in modo proattivo i sistemi che stanno raggiungendo i limiti di capacità e invia una richiesta per aumentare la capacità del tuo sistema storage.

Per ONTAP, è possibile visualizzare sistemi che hanno superato il 90% della capacità o che devono superare il 90% della capacità nei mesi di 1, 3 e 6. Per StorageGRID, è possibile visualizzare sistemi che hanno superato il 70% della capacità o che devono superare il 70% della capacità nei mesi di 1, 3 e 6.

.Fasi
. Nel widget *Pianificazione*, seleziona *espansione dello storage*.
+
Per impostazione predefinita, vengono visualizzati i sistemi ONTAP che hanno superato il 90% della capacità o si stanno avvicinando al 90% della capacità.

. Seleziona la scheda *StorageGRID* per visualizzare i sistemi StorageGRID che hanno superato il 70% della capacità o si stanno avvicinando al 70% della capacità.
. Selezionare i sistemi per i quali si desidera aumentare la capacità.
. Seleziona *Visualizza previsioni di capacità* per visualizzare la previsione di capacità per i prossimi 6 mesi.
. Seleziona *Richiedi aggiunta di capacità*.
. Se lo desideri, fornisci eventuali commenti.
. Seleziona *Invia* per inviare la richiesta al team di storage NetApp per aiutarti con l'espansione dello storage per i sistemi selezionati.

