---
sidebar: sidebar 
permalink: task_add_watchlist.html 
keywords: dashboard, watchlist, add watchlist 
summary: Fornisce informazioni per aggiungere un elenco di controllo alla dashboard. 
---
= Crea una watchlist in Digital Advisor
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
È possibile creare una watchlist per accedere in modo rapido e semplice a un set di sistemi di archiviazione. È possibile aggiungere i sistemi di archiviazione in base alla categoria o al numero di serie.


NOTE: È possibile aggiungere un massimo di 15.000 sistemi di archiviazione in una categoria e 500 sistemi di archiviazione in un numero di serie.

.Fasi
. Nel riquadro di sinistra, fare clic su *Watchlist*
+
Viene visualizzata la schermata *Manage Watchlist* (Gestisci lista di controllo).

. Fare clic su *Create Watchlist* (Crea lista di controllo).
. Fornire un nome per la lista di controllo.
. Selezionare una delle seguenti opzioni per aggiungere sistemi di archiviazione alla lista di controllo:
+
** *Categoria*: Questa opzione consente di aggiungere l'intero inventario associato a una categoria specifica, ad esempio gli abbonamenti a clienti, siti, gruppi o Keystone, alla tua lista di controllo.
+

NOTE: L'opzione *Keystone Subscription* consente di includere qualsiasi numero di iscrizione associato agli abbonamenti Keystone. Quando si esegue una ricerca in base a una lista di controllo, è possibile visualizzare le iscrizioni nel widget *Keystone Subscriptions* sul dashboard di Digital Advisor. Per ulteriori informazioni, vedere link:https://docs.netapp.com/us-en/keystone-staas/integrations/keystone-aiq.html#search-by-keystone-watchlists["Ricerca per elenchi di controllo Keystone"^].

** *Numero di serie*: Questa opzione consente di includere l'inventario nella lista di controllo in base ai numeri di serie specificati. È possibile inserire direttamente il numero di serie o selezionare i numeri di serie da categorie quali cliente, sito o gruppo.


. Fare clic su *Create Watchlist* (Crea lista di controllo).
+
Viene visualizzata la dashboard dell'elenco di controllo.


