---
sidebar: sidebar 
permalink: task_view_inventory_details.html 
keywords: inventory, platforms, systems, clusters, sites 
summary: 'Fornisce informazioni sull"inventario complessivo di proprietà dell"utente.' 
---
= Visualizza i dettagli dell'inventario del tuo sistema di archiviazione in Digital Advisor
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Il widget *Inventario* fornisce un riepilogo di tutti i sistemi e degli switch autorizzati al supporto di cui sei proprietario.  Sono inclusi sia i prodotti abilitati che quelli non abilitati Digital Advisor .

È inoltre possibile generare il report dell'elenco di controllo selezionato e inviarlo via email a un massimo di 5 destinatari.

video::ttbpbT5uTBI[youtube,width=848,height=480]


[[view-system-details]]
== Visualizza i dettagli del sistema

.Fasi
. Nel widget *Inventario*, seleziona *Sistemi* per visualizzare le informazioni di sistema di tutte le piattaforme oppure seleziona il tipo di piattaforma e poi seleziona *Sistemi* per visualizzare i sistemi specifici di quella piattaforma.
. Seleziona il nodo o il cluster per visualizzare informazioni dettagliate sul sistema.
. Seleziona *Download* per scaricare il report *Inventory* e visualizzare i dettagli del sistema in formato .xls.
. Seleziona *Scarica* per scaricare il report *Ansible Inventory* per visualizzare i dettagli del sistema nei formati .yml e .ini a livello di regione o sito.
+
I file Ansible Inventory possono essere utilizzati con file Ansible Playbook personalizzati per apportare modifiche alla configurazione dell'infrastruttura.





[[view-support-entitled-switch-details]]
== Visualizza i dettagli del supporto autorizzato

.Fasi
. Nel widget *Inventario*, seleziona *Switch con diritto all'assistenza* per visualizzare le informazioni su tutti gli switch con diritto all'assistenza.

