---
sidebar: sidebar 
permalink: task_identify_capacity_system.html 
keywords: capacity, space, increase, ONTAP systems, StorageGRID 
summary: Fornisce informazioni per aumentare la capacità del sistema. 
---
= Identificare i sistemi che raggiungono i limiti di capacità
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Identifica in modo proattivo i sistemi che stanno raggiungendo i limiti di capacità e invia una richiesta per aumentare la capacità del tuo sistema storage.

Per ONTAP, è possibile visualizzare sistemi che hanno superato il 90% della capacità o che devono superare il 90% della capacità nei mesi di 1, 3 e 6. Per StorageGRID, è possibile visualizzare sistemi che hanno superato il 70% della capacità o che devono superare il 70% della capacità nei mesi di 1, 3 e 6.

.Fasi
. Nel widget *Pianificazione*, fare clic su *aggiunte di capacità*.
+
Per impostazione predefinita, vengono visualizzati i sistemi ONTAP che hanno superato il 90% della capacità o si stanno avvicinando al 90% della capacità.

. Fare clic sulla scheda *StorageGRID* per visualizzare i sistemi StorageGRID che hanno superato il 70% della capacità o si stanno avvicinando al 70% della capacità.
. Selezionare i sistemi per i quali si desidera aumentare la capacità.
. Fare clic su *View Capacity forecast* (Visualizza previsione capacità) per visualizzare la previsione della capacità per i prossimi 6 mesi.
. Fare clic su *richiesta di aggiunta capacità*.
. Se lo desideri, fornisci eventuali commenti.
. Fare clic su *Invia* per inviare la richiesta al team di archiviazione NetApp per fornire assistenza sull'aggiunta di capacità per i sistemi selezionati.

