---
sidebar: sidebar 
permalink: view-firmware-update-recommendations.html 
keywords: upgrade advisor, firmware recommendations, storage firmware, sp bmc firmware, system files, security files 
summary: Visualizza i suggerimenti di aggiornamento del firmware dello storage, del firmware SP/BMC, dei file di sistema e dei file di sicurezza. 
---
= Visualizza i consigli per l'aggiornamento del firmware in Digital Advisor
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
I clienti possono ora risparmiare tempo e fatica consentendo a Control Tower di aggiornare automaticamente i propri sistemi con le versioni più recenti del firmware, eliminando la necessità di interventi o pianificazioni manuali. Questo aggiornamento riduce il rischio di problemi dovuti a versioni firmware obsolete o incompatibili, garantendo prestazioni, stabilità e protezione ottimali del sistema.

I clienti riceveranno notifiche e avvisi tempestivi sullo stato degli aggiornamenti firmware, con opzioni per attivare le impostazioni AutoSupport e di aggiornamento automatico.

.Fasi
. Nella pagina del pannello di controllo, seleziona *Altri consigli* nel widget *Upgrade Advisor*.
. Seleziona *Visualizza consigli* per visualizzare l'elenco dei consigli.
. Nella colonna *Stato aggiornamento*, seleziona *Vedi avanzamento* per visualizzare i cluster idonei all'aggiornamento.
. In caso di problemi, seleziona i rispettivi link per visualizzare i passaggi per risolverli.

